### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mengruzhu** [Potato-DiGua/didi#1]
为啥运行不了登陆不了www你是建了一个服务器吗，能发一下数据表吗，谢谢谢谢！！

**Comment by Potato-DiGua** [comment]
https://github.com/Potato-DiGua/didiServer 服务器端
数据表已经没有了

**Comment by mengruzhu** [comment]
> https://github.com/Potato-DiGua/didiServer 服务器端
> 数据表已经没有了

还有印象吗 好吧qwq

**Comment by Potato-DiGua** [comment]
时间比较长了，已经没有印象了。你可以根据sql逆推一下。。。
